version: '3.7'

services:

  db:
    image: postgres:15.2-alpine
    env_file:
      - ./.env
    volumes:
      - /var/lib/postgresql/data/


  backend:
    image: vartexxx/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    depends_on:
    - backend
    image: vartexxx/frontend:latest
    volumes:
      - frontend_value:/app/result_build/

  nginx:
    depends_on:
      - frontend
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - frontend_value:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
  frontend_value: