# Generated by Django 4.1.7 on 2023-04-13 09:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ингредиент', max_length=200, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Введите единицу измерения', max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=200, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(help_text='Введите цвет тега', max_length=7, verbose_name='Цвет тега')),
                ('slug', models.SlugField(help_text='Введите уникальный идентификатор', max_length=200, validators=[django.core.validators.RegexValidator(message='Уникальный идентификатор введен неккоректно', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Уникальный идентификатор')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=200, verbose_name='Название рецепта')),
                ('image', models.FileField(help_text='Добавьте фотографию блюда', upload_to='recipe_img/', verbose_name='Фотография блюда')),
                ('text', models.TextField()),
                ('cooking_time', models.PositiveIntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления блюда не может быть меньше 1 минуты')], verbose_name='Время приготовления в минутах')),
                ('author', models.ForeignKey(help_text='Введите пользователя(автора) рецепта', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь(автор) рецепта')),
                ('ingredients', models.ManyToManyField(help_text='Выберите ингредиенты', to='recipes.ingredients', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(help_text='Выберите теги', to='recipes.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-id',),
            },
        ),
        migrations.AddConstraint(
            model_name='recipes',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_recipes'),
        ),
    ]
